language: java
jdk:
- oraclejdk11
- openjdk11
before_deploy:
  - export RELEASE_PKG_FILE=$(ls ./target/*-release.jar)
  - echo "deploying $RELEASE_PKG_FILE to GitHub releases"
deploy:
  provider: releases
  api_key:
    secure: iLmC5cFKxNwuRQ77FuZmlIzeVq3JSwSaDzHA6tZQy21qw7N0EOuSiiNqR7fworkN1zNId+wlZo8IVL9QM2nZjCtXm57Uv8nCgQAA9AgnfNFEG1yP/bgYMLCf04RL6RWkxdP/dPKXJop2zoAVYx9IxDHmxc9P69pHFzTeSQ0oS2M/bsHTC9JU0KZSKOe/HDyfIgrQ8UdlEZunOk5jFUkvkmeg8XLycvthHBZHRf2iD7/PhRgn7oz2mrvS1A1kDv0gu8QPrAr64rr/JxuRwR8mdyA5Z9ug76gWvCCAJ3cTa+UsI4aqtFGB+5ycLkm77qWPx7EtvtBlk/XqXXdUSs4VQyS1iwDb1N4gMs5FNsn7j9NRoo+WJfqO0uUCLGZ/q1X6qz9SCKp7S+/wNt0Mk/YhNoWNMJZMuEhRKQHCEnrBI6f/2qaqjjnuhlBaHIXixLPYeA7xF9DBKeBC1XdPUqjzoIbJus+CQgA6E25p+f7xq5md9xL3lLFSq1uk67qgUrEVts2NgKv7TXKp2k/LT2zexrPXVc/QR9nMGKufhzYQQ2jW7S3XYP4qkt1XiF7TSXmF535ncO+UJEQ+pJjc6EsJ/5FZIZcWCfcH0GDTBokdEles9sdAjzMCU3dNcp6PF3/HkG0hHGcQfSbRAn8z3pn/hWO19ibkVasgf/WM3XHe1IA=
  file_glob: true
  file: "${RELEASE_PKG_FILE}"
  skip_cleanup: true
  on:
    tags: true
    repo: keenan-v1/MapViewer
